# frozen_string_literal: true

source "https://rubygems.org"

gem "data_shifter", path: "../.."

gem "rails", "~> 7.0"
gem "sqlite3", "~> 2.0"

group :test do
  gem "csv" # exercises inline_csv in specs; not a runtime dependency (see data_shifter.gemspec) since it's opt-in
  gem "factory_bot_rails", "~> 6.0"
  gem "rspec-rails", "~> 7.0"
  gem "sidekiq", "~> 8.0"
end
